### 이메일 인증 코드 요청 - 회원가입
POST http://localhost:8080/verifications/email/request
Content-Type: application/json
Accept: application/json

{
  "targetEmail": "student99@test.com",
  "purpose": "SIGNUP"
}


### 이메일 인증 코드 확인 - 회원가입
POST http://localhost:8080/verifications/email/confirm
Content-Type: application/json
Accept: application/json

{
  "targetEmail": "student99@test.com",
  "purpose": "SIGNUP",
  "code": "ZQO89G9G"
}