spring:
  application:
    name: sashimi

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  sql:
    init:
      mode: never

  flyway:
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/be1
      - classpath:db/migration/be2
      - classpath:db/migration/be3
      - classpath:db/migration/be4
      - classpath:db/migration/be5
    baseline-on-migrate: true
    encoding: UTF-8
    out-of-order: true


  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

jwt:
  access-token-validity-in-milliseconds: 10800000
  refresh-token-validity-in-milliseconds: 1209600000

gemini:
  model: gemini-2.0-flash
  base-url: https://generativelanguage.googleapis.com/v1beta
  timeout-seconds: 30

toss:
  payments:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY:}
    connect-timeout: 3s
    read-timeout: 5s

external:
  ncs:
    base-url: https://apis.data.go.kr/B490007/ncsInfo
    service-key: ${NCS_SERVICE_KEY}
    num-of-rows: 100

  qualification-exam-schedule:
    base-url: https://apis.data.go.kr/B490007/qualExamSchd
    service-key: ${QUALIFICATION_EXAM_SERVICE_KEY}
    num-of-rows: 50

  qualification-code:
    base-url: http://openapi.q-net.or.kr/api/service/rest/InquiryListNationalQualifcationSVC
    service-key: ${QUALIFICATION_CODE_SERVICE_KEY}

# 배포 시 환경 변수를 정상적으로 사용하는 방법

# 1. 구성 편집에 들어있는 환경 변수들을 별도의 파일에 작성한다. ex) .env or application-prod 해당 파일에.
# 2. 해당 파일은 유출되면 안되기 때문에 .gitignore 시킨다.
# 3. 만약 , github actions 로 cicd 환경 == 자동배포 환경을 구성하려면
# ignore 시킨 파일을 알아야만 한다.
# 4. 이 때 사용할 수 있는 것이 1 번 파일을 git secrets 에 등록한다.
# 5. 해당 secrets 를 cicd yml 에서 알 수 있게 만든다.
