spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sixsashimi_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sashimi
    password: sashimi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${MAILGUN_SMTP_USERNAME:}
    password: ${MAILGUN_SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: this-is-sashimi-lms-jwt-secret-key-for-hs256-authentication

gemini:
  api-key: ${GEMINI_API_KEY:}

clova:
  ocr:
    secret-key: TW93eU96U2RhSUpJRXR6QVpJYUVxcUJRbk50d0JrQko=
    invoke-url: https://cnitm0kz6m.apigw.ntruss.com/custom/v1/53484/6ed598fe378e0d584cb51da89de9ba074ac75e4af008751114b74abac0481f2b/general

app:
  mail:
    from: ${MAIL_FROM:no-reply@sashimi.com}
