spring:


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  sql:
    init:
      mode: never

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    encoding: UTF-8


  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-validity-in-milliseconds: 10800000
  refresh-token-validity-in-milliseconds: 1209600000

gemini:
  model: gemini-2.0-flash
  base-url: https://generativelanguage.googleapis.com/v1beta
  timeout-seconds: 30

toss:
  payments:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY:}
