### 아이디 중복 확인
GET http://localhost:8080/auth/login-id/check?loginId=user123
Accept: application/json


### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json
Accept: application/json

{
  "loginId": "user123",
  "password": "Password123!",
  "passwordConfirm": "Password123!",
  "email": "barkmin9@naver.com",
  "name": "박민서"
}


### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "loginId": "user123",
  "password": "Password123!"
}
### 토큰 재발급
POST http://localhost:8080/auth/reissue
Content-Type: application/json
Accept: application/json

{
"refreshToken": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiaWF0IjoxNzc5NjE5MTI5LCJleHAiOjE3ODA4Mjg3Mjl9.t4_xINpGOcrN9HPGRrxf-YLuqdi1f1MxWHzvDPlQF8t4ViS1Ae7JwG4QXc-AVaCq"
}


### 로그아웃
POST http://localhost:8080/auth/logout
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiaWF0IjoxNzc5NjE5MTg4LCJleHAiOjE3ODA4Mjg3ODh9.l9l6dJ1tJxVTlL7hIZV7MnbTpoUPGq3u3Xs-VizfekddSjl0K12_lYxVkooDhU3Z"
}

### 관리자 API - 토큰 없음이면 401 정상
GET http://localhost:8080/admin/test
Accept: application/json

### 관리자 API - 학생 토큰이면 403 정상
GET http://localhost:8080/admin/test
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiYXV0aCI6IlJPTEVfU1RVREVOVCIsImlhdCI6MTc3OTYxOTQ4NCwiZXhwIjoxNzc5NjIzMDg0fQ.KT3YFOcmvS2GwVIdrZNsmUH_mS7sm0nccjKCaXrN3KN-rNN0HjjpWjHzv5BkbpnW
Accept: application/json