### 아이디 중복 확인
GET http://localhost:8080/auth/login-id/check?loginId=user123
Accept: application/json


### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json
Accept: application/json

{
  "loginId": "testuser01",
  "password": "Password1!",
  "passwordConfirm": "Password1!",
  "email": "bark9@test.com",
  "name": "테스트회원",
  "birthDate": "2000-01-01",
  "interestCategoryIds": [1, 3],
  "referralCode": "STD001"
}



### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "loginId": "student01",
  "password": "student"
}
### 토큰 재발급
POST http://localhost:8080/auth/reissue
Content-Type: application/json
Accept: application/json

{
"refreshToken": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiaWF0IjoxNzc5NzIxNjY5LCJleHAiOjE3ODA5MzEyNjl9.grQcVmCI8s7UV9YbHn8WHDewM6nEu2gvxH1sx_nTnkBZKMDG7ml2Vh8pPihgf32l"
}


### 로그아웃
POST http://localhost:8080/auth/logout
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzdHVkZW50MDEiLCJpYXQiOjE3Nzk4MDUxNTUsImV4cCI6MTc4MTAxNDc1NX0.xbNpKrHkaYIDK-WCygTLjnBSsQnfqSs09WSyB6FxHIj5mZNtbVI7xpea9U22zEVn"
}

### 관리자 API - 토큰 없음이면 401 정상
GET http://localhost:8080/admin/test
Accept: application/json

### 관리자 API - 학생 토큰이면 403 정상
GET http://localhost:8080/admin/test
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiYXV0aCI6IlJPTEVfU1RVREVOVCIsImlhdCI6MTc3OTYxOTQ4NCwiZXhwIjoxNzc5NjIzMDg0fQ.KT3YFOcmvS2GwVIdrZNsmUH_mS7sm0nccjKCaXrN3KN-rNN0HjjpWjHzv5BkbpnW
Accept: application/json