-- 강사 신청 더미 데이터: PENDING 10개 + REJECTED 10개
-- test01~test20 유저 사용 (V3.4.5에서 생성)

-- =====================
-- PENDING (대기) 10개
-- =====================
INSERT INTO instructor_profiles
    (user_id, bio, motivation_letter, category_id, portfolio_url,
     profile_image_path, resume_file_path, main_careers, approval_status,
     approved_at, created_at, updated_at)
VALUES
    ((SELECT user_id FROM users WHERE login_id = 'test01'),
     '정보처리기사 자격증 보유. 백엔드 개발 4년 경력으로 실무 중심 강의를 희망합니다.',
     'Spring Boot와 JPA를 활용한 실무 경험을 바탕으로 취업 준비생에게 실질적인 도움이 되고 싶습니다.',
     1, 'https://github.com/test01',
     'instructor-applications/profile/test01.jpg',
     'instructor-applications/resume/test01.docx',
     '["Spring Boot 백엔드 개발 (4년)", "AWS 인프라 운영 (2년)", "정보처리기사 취득 (2021)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test02'),
     '네트워크관리사 2급 보유. 네트워크 및 보안 분야 강의를 희망합니다.',
     '현업 네트워크 엔지니어로서의 경험을 나누고 싶습니다.',
     2, 'https://github.com/test02',
     'instructor-applications/profile/test02.jpg',
     'instructor-applications/resume/test02.docx',
     '["네트워크 인프라 설계 (5년)", "보안 취약점 분석 (3년)", "네트워크관리사 2급 취득 (2020)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test03'),
     '리눅스마스터 1급 보유. 리눅스 서버 관리 강의를 희망합니다.',
     '서버 운영 경험을 통해 실무적인 내용을 전달하고 싶습니다.',
     1, 'https://github.com/test03',
     'instructor-applications/profile/test03.jpg',
     'instructor-applications/resume/test03.docx',
     '["Linux 서버 운영 (6년)", "Docker/Kubernetes 관리 (3년)", "리눅스마스터 1급 취득 (2019)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test04'),
     '정보보안기사 보유. 보안 분야 강의를 희망합니다.',
     '보안 취약점 분석 및 대응 경험을 강의로 전달하고 싶습니다.',
     2, 'https://github.com/test04',
     'instructor-applications/profile/test04.jpg',
     'instructor-applications/resume/test04.docx',
     '["보안 컨설팅 (4년)", "취약점 분석 (3년)", "정보보안기사 취득 (2022)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test05'),
     'SQLD 자격증 보유. 데이터베이스 강의를 희망합니다.',
     'SQL 최적화 및 데이터 모델링 경험을 공유하고 싶습니다.',
     1, 'https://github.com/test05',
     'instructor-applications/profile/test05.jpg',
     'instructor-applications/resume/test05.docx',
     '["데이터베이스 설계 (5년)", "SQL 튜닝 (4년)", "SQLD 취득 (2021)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test06'),
     '빅데이터분석기사 보유. 데이터 분석 강의를 희망합니다.',
     '머신러닝과 데이터 분석 실무 경험을 나누고 싶습니다.',
     2, 'https://github.com/test06',
     'instructor-applications/profile/test06.jpg',
     'instructor-applications/resume/test06.docx',
     '["데이터 분석 (3년)", "Python ML 개발 (2년)", "빅데이터분석기사 취득 (2022)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test07'),
     '정보처리기사 보유. 프론트엔드 강의를 희망합니다.',
     'React와 TypeScript 실무 경험을 기반으로 강의하고 싶습니다.',
     1, 'https://github.com/test07',
     'instructor-applications/profile/test07.jpg',
     'instructor-applications/resume/test07.docx',
     '["React 프론트엔드 개발 (4년)", "TypeScript 적용 (3년)", "정보처리기사 취득 (2020)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test08'),
     'AWS SAA 자격증 보유. 클라우드 강의를 희망합니다.',
     'AWS 클라우드 아키텍처 설계 경험을 공유하고 싶습니다.',
     2, 'https://github.com/test08',
     'instructor-applications/profile/test08.jpg',
     'instructor-applications/resume/test08.docx',
     '["AWS 클라우드 아키텍처 (4년)", "DevOps 운영 (3년)", "AWS SAA 취득 (2021)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test09'),
     '정보처리기사 보유. 알고리즘 및 자료구조 강의를 희망합니다.',
     '코딩테스트 준비 경험을 나누며 취업 준비생을 돕고 싶습니다.',
     1, 'https://github.com/test09',
     'instructor-applications/profile/test09.jpg',
     'instructor-applications/resume/test09.docx',
     '["알고리즘 튜터링 (3년)", "코딩테스트 강의 (2년)", "정보처리기사 취득 (2022)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test10'),
     '전자계산기조직응용기사 보유. 컴퓨터 구조 강의를 희망합니다.',
     '하드웨어와 소프트웨어의 연계를 실무 관점에서 가르치고 싶습니다.',
     2, 'https://github.com/test10',
     'instructor-applications/profile/test10.jpg',
     'instructor-applications/resume/test10.docx',
     '["시스템 아키텍처 설계 (5년)", "임베디드 개발 (3년)", "전자계산기조직응용기사 취득 (2019)"]',
     'PENDING', NULL, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY));

-- =====================
-- REJECTED (반려) 10개
-- =====================
INSERT INTO instructor_profiles
    (user_id, bio, motivation_letter, category_id, portfolio_url,
     profile_image_path, resume_file_path, main_careers, approval_status,
     rejection_category, rejection_reason, approved_at, created_at, updated_at)
VALUES
    ((SELECT user_id FROM users WHERE login_id = 'test11'),
     '자격증 취득 후 강의 활동을 시작하고 싶습니다.',
     '열심히 가르쳐 보겠습니다.',
     1, 'https://github.com/test11',
     'instructor-applications/profile/test11.jpg',
     'instructor-applications/resume/test11.docx',
     '["프리랜서 개발 (1년)"]',
     'REJECTED', 'INSUFFICIENT_CAREER_PROOF', '경력을 증빙할 수 있는 서류가 부족합니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test12'),
     '개발자 지망생으로 강의를 통해 성장하고 싶습니다.',
     '배우면서 가르치는 방식으로 진행하고 싶습니다.',
     2, 'https://github.com/test12',
     'instructor-applications/profile/test12.jpg',
     'instructor-applications/resume/test12.docx',
     '["개인 프로젝트 (6개월)"]',
     'REJECTED', 'INSUFFICIENT_BASIC_INFO', '자기소개 및 강의 계획이 구체적이지 않습니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 19 DAY), DATE_SUB(NOW(), INTERVAL 17 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test13'),
     '다양한 분야의 강의를 진행하고 싶습니다.',
     '여러 기술을 두루 알고 있습니다.',
     1, 'https://github.com/test13',
     'instructor-applications/profile/test13.jpg',
     'instructor-applications/resume/test13.docx',
     '["다양한 IT 업무 (2년)"]',
     'REJECTED', 'INSUFFICIENT_CAREER_PROOF', '제출된 자격증 정보와 경력이 일치하지 않습니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test14'),
     '부업으로 강의를 진행하고 싶습니다.',
     '시간이 날 때 강의 자료를 준비하겠습니다.',
     2, 'https://github.com/test14',
     'instructor-applications/profile/test14.jpg',
     'instructor-applications/resume/test14.docx',
     '["회사원 (3년)"]',
     'REJECTED', 'INSUFFICIENT_BASIC_INFO', '강의에 대한 구체적인 계획과 의지가 확인되지 않습니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 17 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test15'),
     '온라인 강의 경험이 없지만 도전하고 싶습니다.',
     '처음이지만 열심히 하겠습니다.',
     1, 'https://github.com/test15',
     'instructor-applications/profile/test15.jpg',
     'instructor-applications/resume/test15.docx',
     '["IT 관련 아르바이트 (1년)"]',
     'REJECTED', 'UNABLE_TO_VERIFY_IDENTITY', '본인 확인 서류가 제출되지 않았습니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 16 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test16'),
     '현재 취업 준비 중이며 강의도 병행하고 싶습니다.',
     '공부한 내용을 강의로 나누겠습니다.',
     2, 'https://github.com/test16',
     'instructor-applications/profile/test16.jpg',
     'instructor-applications/resume/test16.docx',
     '["학원 조교 (6개월)"]',
     'REJECTED', 'INSUFFICIENT_CAREER_PROOF', '강사로서의 전문 경력이 충분하지 않습니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test17'),
     '유튜브 영상을 보고 독학한 내용을 강의하고 싶습니다.',
     '독학으로 익힌 기술을 나누겠습니다.',
     1, 'https://github.com/test17',
     'instructor-applications/profile/test17.jpg',
     'instructor-applications/resume/test17.docx',
     '["독학 프로젝트 (1년)"]',
     'REJECTED', 'INAPPROPRIATE_CAREER_INCLUDED', '이력에 검증되지 않은 경력이 포함되어 있습니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test18'),
     '관련 자격증은 없지만 실무 경험이 있습니다.',
     '현장 경험을 바탕으로 강의하겠습니다.',
     2, 'https://github.com/test18',
     'instructor-applications/profile/test18.jpg',
     'instructor-applications/resume/test18.docx',
     '["소규모 업체 개발 (2년)"]',
     'REJECTED', 'UNABLE_TO_VERIFY_IDENTITY', '제출된 서류만으로는 경력 확인이 어렵습니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test19'),
     '부트캠프 수료 후 강의에 도전하고 싶습니다.',
     '수료 경험을 바탕으로 예비 개발자를 돕고 싶습니다.',
     1, 'https://github.com/test19',
     'instructor-applications/profile/test19.jpg',
     'instructor-applications/resume/test19.docx',
     '["부트캠프 수료 (6개월)", "개인 프로젝트 (3개월)"]',
     'REJECTED', 'INSUFFICIENT_CAREER_PROOF', '실무 경력이 확인되지 않아 반려합니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),

    ((SELECT user_id FROM users WHERE login_id = 'test20'),
     '해외 경력이 있으나 국내 자격증은 없습니다.',
     '해외 경험을 국내 수강생과 나누고 싶습니다.',
     2, 'https://github.com/test20',
     'instructor-applications/profile/test20.jpg',
     'instructor-applications/resume/test20.docx',
     '["해외 IT 기업 근무 (3년)"]',
     'REJECTED', 'UNABLE_TO_VERIFY_IDENTITY', '해외 경력 증빙 서류를 확인할 수 없습니다.',
     NULL, DATE_SUB(NOW(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY));
