services:
  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: sashimi-node-exporter
    restart: unless-stopped
    mem_limit: 32m
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - agent-net

  promtail:
    image: grafana/promtail:2.9.8
    container_name: sashimi-promtail
    restart: unless-stopped
    mem_limit: 32m
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - sashimi-logs:/logs:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - agent-net

networks:
  agent-net:
    name: agent-net

volumes:
  sashimi-logs:
    external: true
