### 내 정보 수정
PATCH http://localhost:8080/users/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiYXV0aCI6IlJPTEVfU1RVREVOVCIsImlhdCI6MTc3OTYyMTk1NiwiZXhwIjoxNzc5NjI1NTU2fQ.99PR4voPvQrx1lAs38OXj1sdmCL9nWIvfDt0UnIc1VOrYLFrs6l8vJH7ahXoLMcQ

{
  "currentPassword": "Password123!",
  "name": "박민서",
  "email": "updated-user123@test.com"
}


### 비밀번호 수정
PATCH http://localhost:8080/users/me/password
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiYXV0aCI6IlJPTEVfU1RVREVOVCIsImlhdCI6MTc3OTYyMTk1NiwiZXhwIjoxNzc5NjI1NTU2fQ.99PR4voPvQrx1lAs38OXj1sdmCL9nWIvfDt0UnIc1VOrYLFrs6l8vJH7ahXoLMcQ

{
  "currentPassword": "Password123!",
  "newPassword": "NewPassword123!",
  "newPasswordConfirm": "NewPassword123!"
}


### 회원 탈퇴
DELETE http://localhost:8080/users/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiYXV0aCI6IlJPTEVfU1RVREVOVCIsImlhdCI6MTc3OTYyMjI0OCwiZXhwIjoxNzc5NjI1ODQ4fQ.X6VewSWHQ2zenwQEuA8w4GIzT56JzASnUOiRMfezT9ynqt0jFIKh9ZNWMWpLBj-g

{
  "currentPassword": "NewPassword123!"
}