ALTER TABLE users
    ADD COLUMN marketing_consent BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN email_consent     BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN ai_consent        BOOLEAN NOT NULL DEFAULT FALSE;
