ALTER TABLE instructor_profiles
    ADD COLUMN rejection_category ENUM('INSUFFICIENT_CAREER_PROOF', 'INSUFFICIENT_BASIC_INFO', 'UNABLE_TO_VERIFY_IDENTITY', 'INAPPROPRIATE_CAREER_INCLUDED') NULL,
    ADD COLUMN rejection_reason VARCHAR(100) NULL;
